### PR TITLE
Added InsertEntity to the TableClient

### PR DESCRIPTION
**Pull request by richorama**
And some tests :¬S

### CODE REVIEW

**Comment by AndyCross** [comment]
I had recently added a method "InsertEntity" - I take in an object which also contains the type of the property.

**Comment by richorama** [comment]
Nuts.

**Comment by richorama** [comment]
Do you work out the type automagically?

**Comment by AndyCross** [comment]
Nope, it’s a string! :D

**Comment by richorama** [comment]
Oh well, it was time well spent just getting up to speed on netmf.

**Comment by AndyCross** [comment]
:-( WHERE MY PULL REQUEST GO! You fixed loadsa stuff!

**Comment by richorama** [comment]
I closed it. You can re-open I think.

**Pull request merged**
